### ISSUE TITLE
Typo on /ATP/APEX/L200.md

### ISSUE THREAD

**Issue by vmleon** [oracle/cloudtestdrive#14]
The escape characters for javascript expression to concatenate the postcode and the city needs a new line (return) on the last line to be properly rendered.

Let me know if administrator prefers a pull request.

[Link to file](https://github.com/vmleon/cloudtestdrive/blob/master/ATP/APEX/L200.md)
```
", " +
$v("P6_POSTAL_CODE").replace(",", " ") + 
", " +
$v("P6_CITY").replace(",", " ")
```

Vs.

```
", " +
$v("P6_POSTAL_CODE").replace(",", " ") + 
", " +
$v("P6_CITY").replace(",", " ")```
This line doesn't belong to this code snippet. but the triple quote in previous line mess it around.

**Comment by janleemans** [comment]
Corrected in update by Jeroen
