### ISSUE TITLE
Question to Oracle webcast event: Live Virtual Lab: Microservices on Kubernetes and Autonomous Database, 28th November

### ISSUE THREAD

**Issue by teopeckkwan** [oracle/cloudtestdrive#21]
The lab guide:
https://github.com/oracle/cloudtestdrive/blob/master/AppDev/ATP-OKE/README.md

I was at the last step (part 5 , step 6) of the lab exercise and got en error

I might not be at the right forum, then I will like to know where I should send this question to.

At Part 5 step 6 of the lab when I accessing : http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#%21/overview?namespace=default.

I got this error for developments, pods, replica sets, I think the error is because "/opt/oracle/lib/wallet_NODEAPPDB2" cannot be located.

 

.SetUp failed for volume "db-wallet" : secrets "db-wallet" not found

 

my atp2.yaml:

apiVersion: apps/v1beta1

kind: Deployment

metadata:

  name: atp2

spec:

  selector:

    matchLabels:

      app: atp2

  replicas: 1 # deployment runs 1 pods matching the template

  template: # create pods using pod definition in this template

    metadata:

      labels:

        app: atp2

    spec:

      containers:

      - name: atp2

        image: fra.ocir.io/frvptrimr9jb/tpk_repo/atp01:latest

        imagePullPolicy: Always

        volumeMounts:

         - mountPath: "/opt/oracle/lib/wallet_NODEAPPDB2"

           name: db-wallet

           readOnly: true

        ports:

        - containerPort: 3050 #Endpoint is at port 80 in the container

      imagePullSecrets:

      - name: tpk-ocirsecret

      volumes:

        - name: db-wallet

          secret:

            secretName: db-wallet

---

apiVersion: v1

kind: Service

metadata:

  name: atp2

spec:

  type: NodePort #Exposes the service as a node port

  ports:

  - port: 3050

    protocol: TCP

    targetPort: 3050

  selector:

    app: atp2

 

/Kwan

**Comment by aorcl** [comment]
Hello, @janleemans - can you take a look at this?

**Comment by teopeckkwan** [comment]
Yes, will love to get some help!

I solved the problem with ".SetUp failed for volume "db-wallet" : secrets "db-wallet" not found" by editing the file sqlnet.ora.

So I got a bit further now and got another error:
Failed to pull image "fra.ocir.io/frvptrimr9jb/tpk_repo/atp01:latest": rpc error: code = Unknown desc = Get https://fra.ocir.io/v2/frvptrimr9jb/tpk_repo/atp01/manifests/latest: unknown: Invalid username format. Expected format: <tenant name>/<username>

It seems the somewhere I made a mistake in username, I could not locate it.
The username should be: frvptrimr9jb/api.user. 

/Kwan

**Comment by janleemans** [comment]
Concerning the wallet : I recently changed the setup, as to use a secret to make the wallet available to the application running in the pods.  For that, you need to (manually) create that secret via kubectl - see Part 4, the link to the page https://github.com/oracle/cloudtestdrive/blob/master/AppDev/ATP-OKE/LabGuide650BuildDocker_own1.md for when running your own instance

**Comment by janleemans** [comment]
The username/password that is used to pull the image from K8S is also stored in a secret.  See very last part of Step 3.  This is where you need to specify username as 'tenancyname'/'username' (so in your case I guess frvptrimr9jb/api.user ), and the "password is actually the TOKEN you defined for api.user.

**Comment by teopeckkwan** [comment]
Thanks, I got it :)
I did a kubectl delete secret then recreated it with the correct username, reployed and restarted the cluster, then it works!
Have bought two books on MIcroservices, will learn more during the coming Christmas and New Year break. The webcast tutorial was good and I appreciate the help in this forum, Thank you and Happy Christmas.
/Kwan

**Comment by janleemans** [comment]
Happy christmas, closing the issue.
Thanks for the feedback!
