### ISSUE TITLE
unable to create credentials in 19c ATP via admin user 

### ISSUE THREAD

**Issue by asifiqbaloracle** [oracle/cloudtestdrive#40]
facing below issue while trying to create credentials for objects storage on OCI in ATP database instance 
-------------------------------------
Error starting at line : 25 in command -
BEGIN
 DBMS_CREDENTIAL.CREATE_CREDENTIAL(
 credential_name => 'databucket',
 username => 'oracleidentitycloudservice/asif.i.iqbal@oracle.com',
 password => ')VyajgyodXo5S(a36XL4'
 );
 END;
Error report -
ORA-27486: insufficient privileges
ORA-06512: at "SYS.DBMS_CREDENTIAL", line 44
ORA-06512: at "SYS.DBMS_ISCHED", line 2487
ORA-06512: at "SYS.DBMS_CREDENTIAL", line 32
ORA-06512: at line 2
27486. 00000 -  "insufficient privileges"
*Cause:    An attempt was made to perform a scheduler operation without the
           required privileges.
*Action:   Ask a sufficiently privileged user to perform the requested
           operation, or grant the required privileges to the proper user(s).

------------------------------------------------

**Comment by bilegt-bat-ochir** [comment]
have you issued this command from Admin user?

**Comment by bilegt-bat-ochir** [comment]
the user who issues command should have DWROLE role or Admin.

**Comment by asifiqbaloracle** [comment]
yes i am using admin

**Comment by asifiqbaloracle** [comment]
I am able to fix by setting "set define off" before actual commands

**Comment by muhammaduns** [comment]
facing the same issue:

ORA-27486: insufficient privileges ORA-06512: at "SYS.DBMS_CREDENTIAL", line 44 ORA-06512: at "SYS.DBMS_ISCHED", line 2487 ORA-06512: at "SYS.DBMS_CREDENTIAL", line 32 ORA-06512: at line 2
