### ISSUE TITLE
Lab 3 - Step 2 - Terraform Error: Attempt to index null value

### ISSUE THREAD

**Issue by yk5235** [oracle/cloudtestdrive#81]
I am see this error when I try to run terraform plan

Error: Attempt to index null value

  on k8s.tf line 35, in resource "oci_containerengine_node_pool" "K8S_pool1":
  35:       availability_domain = lookup(data.oci_identity_availability_domains.ads.availability_domains[0],"name")
    |----------------
    | data.oci_identity_availability_domains.ads.availability_domains is null

This value is null, so it does not have any indices.

**Comment by janleemans** [comment]
Hello, thanks for pointing this out.  This error occurs when you are running the script in a "single AD" region. Workaround is to remove the blocks in the k8s.ft referring to AD 2 and AD 3. 
I'm working on a more comprehensive solution taking into account effective number of AD's in the region.

**Comment by janleemans** [comment]
Corrected to dynamically take into account nb of AD's in the region.
Please note source code of the corrected script is on https://github.com/CloudTestDrive/ATPDocker.git, you need to re-fork the repo or manually correct k8s.tf
